services:
    app:
        build: .
        environment:
            - bot_token="${CLIENT_TOKEN}"
            - channel_id="${CHANNEL_ID}"
        ports:
            - "443:443"
            - "8080:8080"
        env_file:
          - .env
